# Set up environment.
environment:
  # Run for both architecture for python 3.7.x
  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: "64"

# Set python path.
init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

# Installations.
install:
  # Upgrade pip to the latest version.
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
test_script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Test for unit test.
  - python -m pytest unit_test/

build: off
