# Set up environment.
environment:
  # Run for both architecture for python 3.7.
  matrix:
    - PYTHON: "C:\Python36"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\Python36-x64"
      PYTHON_ARCH: "64"

# Installations.
install:
  # Upgrade pip to the latest version.
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
test_script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Test for unit test.
  - python -m pytest unit_test/

build: off
