# Set the language to be python and adjust environment.
language: python
sudo: required
dist: xenial

# Set the version of python to be the latest version.
python: "3.7"

# Installations.
install:
  # Upgrade pip to the latest version.
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Test for unit test.
  - python -m pytest --cov=unit_test/

# Find code coverage.
after_success: codecov
