# Set the language to be python.
language: python

# Set the version of python to be the latest version.
python:
  - "3.6"
  # - "3.7" This can be enabled after https://github.com/travis-ci/travis-ci/issues/9815 is solved.

# Installations.
install:
  # Upgrade pip to the latest version.
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Test for unit test.
  - python -m pytest unit_test/

# Find code coverage.
after_success:
  - codecov
